language: ruby
rvm:
  - 1.9.3
  - 2.2.0
before_script:
  - chmod 777 ./config/before-travis.sh
  - ./config/before-travis.sh
script:
  - export DISPLAY=:99.0
  - bundle exec rake
branches:
  only:
    - master
